version: '2'

version: "2"
services:
  dmall.order.db:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r5t
    tmpfs:
      - /tmp/order_mysql
    ports:
      - 3312:3306

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins_dmall-network:
    external: true